/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import Negocio.CinemaFachada;
import Negocio.FilmesDAOException;
import Negocio.HorariosDAOException;
import Negocio.Sessoes;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author matthias
 */
public class GUISessoes extends javax.swing.JFrame {

    /**
     * Creates new form GUISessoes
     */
    public GUISessoes(ArrayList<Sessoes> sessoes) {
        CinemaFachada cf = new CinemaFachada();
        initComponents();
        jLabel1.setText(jLabel1.getText() + " " + sessoes.get(0).getDate().toString());
        for (Sessoes s : sessoes) {
            String nomeDoFilme = null;
            String horarioInicio = null;
            String horarioFim = null;
            String vagas = null;
            if (s.getVagas() > 0){
                vagas = "Há vagas";
            }
            else{
                vagas = "Sessao esgotada";
            }
            try {
                nomeDoFilme = cf.buscaFilmePorId(s.getFilmeId());
            } catch (FilmesDAOException ex) {
                Logger.getLogger(GUISessoes.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                horarioInicio = cf.buscarHorarioDeInicioDaSessao(s.getHorarioId());
                horarioFim = cf.buscarHorarioDeFimDaSessao(s.getHorarioId());
            } catch (HorariosDAOException ex) {
                Logger.getLogger(GUISessoes.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLabel2.setText(jLabel2.getText() + "Filme: " + nomeDoFilme + "  ");
            jLabel2.setText(jLabel2.getText() + "Horario de Início: " + horarioInicio + "  ");
            jLabel2.setText(jLabel2.getText() + "Horario de Fim: " + horarioFim + "  ");
            jLabel2.setText(jLabel2.getText() + "Vagas: " + vagas + "  ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("Data:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
